Views
niicode/rails-blog pull request #6
Opened 2022-12-02 08:24 UTC by niicode

In this PR, I added:
Logic to the post index and show
Logic to the users index and show
Partials for the users and view template

2022-12-02 09:36 UTC, fobadara requested changes
# REQUIRES CHANGES ♻️ 
Hi @niicode, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ Linters are passing
✅ Project looks professional


## Required Changes ♻️
_Check the comments under the review._
I had to include. some comments here because they could not be done inline.
[REQUIRED] When I run your migrations I get errors:
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/62938735/205261673-91524107-820b-4d6b-8c51-d75f80cf7d28.png">
Kindly fix this error for further checks from the next reviewer

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 09:36 UTC, fobadara commented on app/views/users/index.html.erb
> +         <%= render 'shared/user', user: user %>
[OPTIONAL] I think you should add a `li` tag here since. you have a `ul` wrapping it

2022-12-02 10:13 UTC, DammyShittu requested changes
Hi @niicode,

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 10:13 UTC, DammyShittu commented on app/views/posts/show.html.erb
> +</div>
-[ ] Kindly style your post show page to match the wireframe: [https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/blog-app/images/blog_user_all_posts.png?token=GHSAT0AAAAAABY4RVENF5O6IYX2BVYE7R7GY4J3RNQ](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/blog-app/images/blog_user_all_posts.png?token=GHSAT0AAAAAABY4RVENF5O6IYX2BVYE7R7GY4J3RNQ)

2022-12-02 10:13 UTC, DammyShittu commented on app/views/posts/show.html.erb
> +    <% @post.recent_five_comments.each do |comment| %>
- [ ] I get this error when I visit the post show page. Kindly fix that. What you have is `last_five_comments`, not `recent_five_comments`.

  ![didow](https://user-images.githubusercontent.com/54848363/205268889-baac972f-acb9-457e-a150-68e2a2347ee6.jpg)

2022-12-02 10:13 UTC, DammyShittu commented on app/views/users/show.html.erb
> +          <%= render 'shared/post', post: post %>
- [ ] Kindly style the post part for the user show page to match the wireframe: [https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/blog-app/images/blog_user_page.png?token=GHSAT0AAAAAABY4RVENCWGONH3SFHF5DZB4Y4J3SSA](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/blog-app/images/blog_user_page.png?token=GHSAT0AAAAAABY4RVENCWGONH3SFHF5DZB4Y4J3SSA)

  ![image](https://user-images.githubusercontent.com/54848363/205269146-df0bd50e-78e6-4da6-bc23-6d09f0911310.png)

2022-12-03 09:02 UTC, EricMbouwe approved these changes
Hi @niicode, 

Your project is complete! ⚡🔥  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🎉🔥
- Views ✔
- No linter errors ✔
- Requested changes ✔

## Optional suggestions ☂

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 09:19 UTC, merged